/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package numeros;

import javax.swing.JOptionPane;

/**
 *
 * @author Daniel
 */
public class agregar extends javax.swing.JFrame {
public int listaNumeros [] = new int [100];
    public int indice = 0;
    /**
     * Creates new form agregar
     */
    public agregar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Numbers = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        Resultado = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Agregar = new javax.swing.JButton();
        Mostrar = new javax.swing.JButton();
        Ordenar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Numbers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumbersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Numbers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(Numbers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 275, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 400, -1));

        jPanel3.setLayout(new java.awt.GridLayout());

        Agregar.setBackground(new java.awt.Color(255, 255, 0));
        Agregar.setText("Agregar");
        Agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AgregarMouseExited(evt);
            }
        });
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });
        jPanel3.add(Agregar);

        Mostrar.setBackground(new java.awt.Color(255, 255, 0));
        Mostrar.setText("Mostrar");
        Mostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MostrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MostrarMouseExited(evt);
            }
        });
        Mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarActionPerformed(evt);
            }
        });
        jPanel3.add(Mostrar);

        Ordenar.setBackground(new java.awt.Color(255, 255, 0));
        Ordenar.setText("Ordenar");
        Ordenar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OrdenarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OrdenarMouseExited(evt);
            }
        });
        Ordenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrdenarActionPerformed(evt);
            }
        });
        jPanel3.add(Ordenar);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 400, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NumbersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumbersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumbersActionPerformed

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        // TODO add your handling code here:
       if (!validarNumeros(Numbers.getText().trim()))
       {
           JOptionPane.showMessageDialog(rootPane, "El dato es incorrecto");
           Numbers.setText("");
       }
       else 
        JOptionPane.showMessageDialog(rootPane, "El dato es correcto y a sido agregado");
       listaNumeros [indice]=Integer.parseInt(Numbers.getText());
       indice++;
       Numbers.setText("");

    }//GEN-LAST:event_AgregarActionPerformed

    private void MostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarActionPerformed
        // TODO add your handling code here:
        String mensaje = " ";
        for (int i=0; i< indice ;i ++)
        {
           mensaje = mensaje + listaNumeros [i]+"-";
           
        }
        Resultado.setText(mensaje);
    }//GEN-LAST:event_MostrarActionPerformed

    private void OrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrdenarActionPerformed
        // TODO add your handling code here:
        for(int i=0; i < (indice-1)  ;i ++)
          {
              for (int j=0;j<(indice-1);j++)
              {
                  if (listaNumeros[j]> listaNumeros [j+1])
                  {
                     int aux= listaNumeros[j];
                      listaNumeros[j]=listaNumeros[j+1];
                      listaNumeros[j+1]= aux;
                  }
              }
          }
        // Mostrar la lista ordenada 
        String mensajeLista = " ";
        for (int i=0;i<indice;i++)
        {
         mensajeLista = mensajeLista + listaNumeros [i]+"-";
        Resultado.setText(mensajeLista);
        }

    }//GEN-LAST:event_OrdenarActionPerformed

    private void AgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarMouseEntered
        // TODO add your handling code here:
        Agregar.setBackground(new java.awt.Color(192, 57, 43));
    }//GEN-LAST:event_AgregarMouseEntered
    

    
    private void MostrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MostrarMouseEntered
        // TODO add your handling code here:
         Mostrar.setBackground(new java.awt.Color(255, 255, 0));
    }//GEN-LAST:event_MostrarMouseEntered

    private void MostrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MostrarMouseExited
        // TODO add your handling code here:
        Mostrar.setBackground(new java.awt.Color(192, 57, 43));
    }//GEN-LAST:event_MostrarMouseExited

    private void AgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarMouseExited
        // TODO add your handling code here:
        Agregar.setBackground(new java.awt.Color(255, 255, 0));
    }//GEN-LAST:event_AgregarMouseExited

    private void OrdenarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrdenarMouseEntered
        // TODO add your handling code here:
         Ordenar.setBackground(new java.awt.Color(255, 255, 0));
    }//GEN-LAST:event_OrdenarMouseEntered

    private void OrdenarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrdenarMouseExited
        // TODO add your handling code here:
         Ordenar.setBackground(new java.awt.Color(192, 57, 43));
    }//GEN-LAST:event_OrdenarMouseExited
public static boolean validarNumeros(String datos)
    {
        return datos.matches("[0-9]*");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new agregar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JButton Mostrar;
    private javax.swing.JTextField Numbers;
    private javax.swing.JButton Ordenar;
    private javax.swing.JLabel Resultado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
